server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
      config:
        server-addr: ${NACOS_SERVER_ADDR}
  config:
    import:
      - nacos:gateway.yaml
      # - optional:nacos:gateway-dev.yaml