server:
  port: 8087
spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr:127.0.0.1:8848
      # config:
      #   server-addr: 127.0.0.1:8848  # Nacos ??????
      #   file-extension: yaml         # ?????????yaml, properties ??
      #   group: DEFAULT_GROUP         # ???????
      #   namespace: public            # ????????
      #   username: nacos              # ?????????
      #   password: nacos              # ????????